# ── Stage 1: builder ──────────────────────────────────────────────────────────
FROM python:3.13-slim AS builder

WORKDIR /app

# Install uv for fast, reproducible dependency resolution
COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

# Copy everything setuptools needs to build the local package
COPY pyproject.toml uv.lock README.md ./
COPY src/ ./src/

# Install only production dependencies into an isolated venv
RUN uv sync --no-dev --frozen

# ── Stage 2: runtime ──────────────────────────────────────────────────────────
FROM python:3.13-slim AS runtime

WORKDIR /app

# Copy the installed venv from the builder stage
COPY --from=builder /app/.venv /app/.venv

# Copy application source
COPY src/ ./src/
COPY main.py ./

# Copy trained model artifact (generated by train_model.py before build)
# The model/ directory is in .gitignore; it must be produced by CI before
# running docker build, or downloaded from a model registry at startup.
COPY model/ ./model/

# Ensure the venv binaries are on PATH
ENV PATH="/app/.venv/bin:$PATH"

EXPOSE 8000

# Heroku injects $PORT at runtime; fall back to 8000 for local Docker runs.
HEALTHCHECK --interval=30s --timeout=5s --start-period=15s --retries=3 \
    CMD python -c "import urllib.request, os; urllib.request.urlopen('http://localhost:' + os.environ.get('PORT', '8000') + '/')"

CMD ["sh", "-c", "uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}"]
